import 'dart:math' as math;

/// A simple complex number class for the FFT implementation.
class Complex {
  final double real;
  final double imag;
  Complex(this.real, this.imag);
  
  Complex operator +(Complex other) => Complex(real + other.real, imag + other.imag);
  Complex operator -(Complex other) => Complex(real - other.real, imag - other.imag);
  Complex operator *(Complex other) => Complex(
      real * other.real - imag * other.imag,
      real * other.imag + imag * other.real);
      
  double get magnitude => math.sqrt(real * real + imag * imag);
}

/// Port of the Python physiological PPG algorithm for calculating Heart Rate (BPM).
/// Does not rely on any native/Python plugins. Fully implements required DSP:
/// centering, interpolation, zero-phase Butterworth filtering, and Welch's PSD estimation.
class PpgAlgorithm {

  /// Given a raw list of red channel average intensities and the elapsed scan duration,
  /// returns the estimated heart rate in BPM.
  static double calculateBPM(List<double> rawRed, double elapsedSeconds) {
    if (elapsedSeconds <= 0 || rawRed.length < 50) return 0.0;

    int numSamples = rawRed.length;
    double actualFps = numSamples / elapsedSeconds;

    // 1. Resample to exactly 30 Hz for consistent IIR filter application
    double targetHz = 30.0;
    int targetCount = (elapsedSeconds * targetHz).round();
    List<double> resampled = [];
    
    for (int i = 0; i < targetCount; i++) {
      double targetTime = i / targetHz;
      double rawIndexStr = targetTime * actualFps;
      int idx0 = rawIndexStr.floor();
      int idx1 = rawIndexStr.ceil();
      if (idx0 < 0) idx0 = 0;
      if (idx1 >= numSamples) idx1 = numSamples - 1;
      
      if (idx0 == idx1) {
        resampled.add(rawRed[idx0]);
      } else {
        double frac = rawIndexStr - idx0;
        resampled.add(rawRed[idx0] * (1 - frac) + rawRed[idx1] * frac);
      }
    }

    // 2. Mean centering
    double redMean = resampled.reduce((a, b) => a + b) / resampled.length;
    List<double> centered = resampled.map((v) => v - redMean).toList();

    // 3. Band-pass filter (40-80 BPM ~ 0.6667 - 1.3333 Hz)
    // Hardcoded coefficients generated by Python scipy.signal.butter(2, [low, high], btype='bandpass') at 30Hz
    List<double> b = [0.004430007511530343, 0.0, -0.008860015023060686, 0.0, 0.004430007511530343];
    List<double> a = [1.0, -3.7290704031502533, 5.287302342101, -3.3776723692206536, 0.8208133180937239];
    
    List<double> filtered = _filtfilt(b, a, centered);

    // 4. Welch's PSD calculation mimicking scipy.signal.welch
    int nperseg = 300;
    if (filtered.length < nperseg) {
      // Fallback if less than 10 seconds of data at 30fps
      nperseg = filtered.length ~/ 2;
      if (nperseg % 2 != 0) nperseg--;
    }
    if (nperseg < 64) return 0.0; // Too little data

    int step = nperseg ~/ 2; // 50% overlap (Scipy default)
    int nfft = _nextPowerOf2(nperseg);
    if (nfft < 512) nfft = 512; // Pad at least to 512 for higher frequency resolution
    
    // Hanning window
    List<double> window = List.generate(nperseg, (n) => 0.5 * (1 - math.cos(2 * math.pi * n / (nperseg))));
    double sumWindowSq = window.fold(0.0, (val, w) => val + w * w);
    
    List<double> avgPsd = List.filled(nfft ~/ 2 + 1, 0.0);
    int segments = 0;

    for (int i = 0; i <= filtered.length - nperseg; i += step) {
      List<Complex> signalSegment = List.generate(nfft, (j) {
        if (j < nperseg) return Complex(filtered[i + j] * window[j], 0);
        return Complex(0, 0); // Zero-padding
      });
      
      List<Complex> fftResult = _fft(signalSegment);
      
      for (int k = 0; k <= nfft ~/ 2; k++) {
        double mag = fftResult[k].magnitude;
        double power = (mag * mag) / (targetHz * sumWindowSq); // Welch normalizes power
        if (k > 0 && k < nfft ~/ 2) power *= 2.0; // Two-sided to one-sided adjustment
        avgPsd[k] += power;
      }
      segments++;
    }

    // 5. Identify peak frequency
    double maxPower = -double.maxFinite;
    double peakFreq = 0.0;
    
    for (int k = 0; k <= nfft ~/ 2; k++) {
      double f = k * targetHz / nfft;
      double power = avgPsd[k] / segments;
      
      // We look at the full PSD for maximum power, mimicking the Python script behavior.
      if (power > maxPower) {
        maxPower = power;
        peakFreq = f;
      }
    }

    // Convert Hz to BPM (multiply by 60)
    return peakFreq * 60.0;
  }

  // Helper: Next power of 2
  static int _nextPowerOf2(int n) {
    int p = 1;
    while (p < n) p <<= 1;
    return p;
  }

  // Fast Fourier Transform (Cooley-Tukey Radix-2)
  static List<Complex> _fft(List<Complex> x) {
    int n = x.length;
    if (n <= 1) return x;
    
    List<Complex> even = _fft(List.generate(n ~/ 2, (i) => x[i * 2]));
    List<Complex> odd = _fft(List.generate(n ~/ 2, (i) => x[i * 2 + 1]));
    
    List<Complex> t = List.generate(n ~/ 2, (k) {
        double angle = -2 * math.pi * k / n;
        Complex w = Complex(math.cos(angle), math.sin(angle));
        return w * odd[k];
    });
    
    List<Complex> res = List.filled(n, Complex(0, 0));
    for (int k = 0; k < n ~/ 2; k++) {
        res[k] = even[k] + t[k];
        res[k + n ~/ 2] = even[k] - t[k];
    }
    return res;
  }

  // Zero-phase forward and reverse digital IIR filtering
  static List<double> _filtfilt(List<double> b, List<double> a, List<double> x) {
    // Equivalent roughly to scipy's Gustafsson padding for zero start edge
    // but a standard forward/backward pass is functionally sufficient for stationary heart signals.
    List<double> forward = _filter(b, a, x);
    List<double> backward = _filter(b, a, forward.reversed.toList()).reversed.toList();
    return backward;
  }

  // Direct Form II Transposed filtering 
  static List<double> _filter(List<double> b, List<double> a, List<double> x) {
    int n = x.length;
    List<double> y = List.filled(n, 0.0);
    List<double> z = List.filled(b.length, 0.0);
    
    for (int i = 0; i < n; i++) {
        y[i] = b[0] * x[i] + z[0];
        for (int j = 1; j < b.length; j++) {
            z[j - 1] = b[j] * x[i] - a[j] * y[i] + (j < b.length - 1 ? z[j] : 0.0);
        }
    }
    return y;
  }
}
